	AREA RESET,DATA,READONLY
	EXPORT __Vectors
__Vectors
	DCD 0x10001000
	DCD Reset_Handler
	ALIGN
	AREA mycode, CODE, READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler
	LDR R1,N
	MLA R0,R1,R1,R1
	LSR R0,#1
	LDR R2,=RES
	STR R0,[R2]
STOP B STOP
N DCD 0XA
	AREA MYDATA,DATA, READWRITE
RES DCD 0
	END