	AREA RESET,DATA,READONLY
	EXPORT __Vectors
__Vectors
	DCD 0x10001000
	DCD Reset_Handler
	ALIGN
	AREA mycode, CODE, READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler
	LDR R0,NUM1
	LDR R1,NUM2
	LDR R3,=RES
	SUBS R5,R0,R1
	ADC R4,#0
	SUB R4,#1 ; CARRY TO BORROW
	STM R3,{R4,R5}
STOP B STOP
NUM1 DCD 0X32ffff32
NUM2 DCD 0XFF
	AREA mydata, DATA, READWRITE
RES DCD 0,0
	END